GET http://localhost:3000

### gauti visus users
GET http://localhost:3000/api/users

### gauti viena user
GET http://localhost:3000/api/users/1


### BOOKS ROUTES ===========

### gauti visus books
GET http://localhost:3000/api/books

### gauti viena book
GET http://localhost:3000/api/books/1

### prideti viena knyga
POST http://localhost:3000/api/books/
Content-Type: application/json

{
  "title": "Book 1",
  "year": 2021,
  "isPublished": true,
  "category": "Fiction"
}


### PEOPLE ROUTES ===========

### gauti visus people
GET http://localhost:3000/api/people

### gauti susituokusius zmones
GET http://localhost:3000/api/people/married

### gauti people algu atlyginimu vidurki
GET http://localhost:3000/api/people/salary/avg
